version: '3.5'

services:
    astatine-api:
        image: ghcr.io/justuseastatine/astatine:7
        restart: unless-stopped
        container_name: astatine-api

        init: true

        # if container doesn't run detached on your machine, uncomment the next line
        #tty: true

        ports:
            - 9000:9000/tcp
            # if you're using a reverse proxy, uncomment the next line and remove the one above (9000:9000/tcp):
            #- 127.0.0.1:9000:9000

        environment:
            # replace https://api.astatine.invalid/ with your instance's target url in same format
            API_URL: "https://api.astatine.invalid/"
            # replace eu-nl with your instance's distinctive name
            API_NAME: "eu-nl"
            # if you want to use cookies when fetching data from services, uncomment the next line and the lines under volume
            # COOKIE_PATH: "/cookies.json"
            # see docs/run-an-instance.md for more information
        labels:
            - com.centurylinklabs.watchtower.scope=astatine

        # if you want to use cookies when fetching data from services, uncomment volumes and next line
        #volumes:
            #- ./cookies.json:/cookies.json

    astatine-web:
        image: ghcr.io/justuseastatine/astatine:7
        restart: unless-stopped
        container_name: astatine-web

        init: true

        # if container doesn't run detached on your machine, uncomment the next line
        #tty: true

        ports:
            - 9001:9001/tcp
            # if you're using a reverse proxy, uncomment the next line and remove the one above (9001:9001/tcp):
            #- 127.0.0.1:9001:9001

        environment:
            # replace https://astatine.invalid/ with your instance's target url in same format
            WEB_URL: "https://astatine.invalid/"
            # replace https://api.astatine.invalid/ with preferred api instance url
            API_URL: "https://api.astatine.invalid/"

        labels:
            - com.centurylinklabs.watchtower.scope=astatine

    # update the astatine image automatically with watchtower
    watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope astatine --interval 900 --include-restarting
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
